spring.application.name=university
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:app_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET_KEY:default-secret}
jwt.expiration=${JWT_EXPIRATION:86400000}
