-- V5__Seed_Subjects_And_Groups.sql
-- Seed subjects and groups extracted from all schedule PDFs (sem. II, 2025/2026)
-- 10 Specializations across all years

-- =============================================
-- Student Groups
-- =============================================
INSERT INTO student_groups (identifier, specialization, year, semester) VALUES
    -- Automatică și Informatică Aplicată (AIA)
    ('1111A', 'Automatică și Informatică Aplicată', 1, 2),
    ('1111B', 'Automatică și Informatică Aplicată', 1, 2),
    ('1111C', 'Automatică și Informatică Aplicată', 1, 2),
    ('1121A', 'Automatică și Informatică Aplicată', 2, 2),
    ('1121B', 'Automatică și Informatică Aplicată', 2, 2),
    ('1121C', 'Automatică și Informatică Aplicată', 2, 2),
    ('1131A', 'Automatică și Informatică Aplicată', 3, 2),
    ('1131B', 'Automatică și Informatică Aplicată', 3, 2),
    ('1141A', 'Automatică și Informatică Aplicată', 4, 2),
    ('1141B', 'Automatică și Informatică Aplicată', 4, 2),

    -- Sisteme Electrice (SE)
    ('1211A', 'Sisteme Electrice', 1, 2),
    ('1211B', 'Sisteme Electrice', 1, 2),
    ('1221A', 'Sisteme Electrice', 2, 2),
    ('1221B', 'Sisteme Electrice', 2, 2),
    ('1231', 'Sisteme Electrice', 3, 2),
    ('1241', 'Sisteme Electrice', 4, 2),

    -- Electronică Aplicată (EA)
    ('1311A', 'Electronică Aplicată', 1, 2),
    ('1311B', 'Electronică Aplicată', 1, 2),
    ('1321A', 'Electronică Aplicată', 2, 2),
    ('1321B', 'Electronică Aplicată', 2, 2),
    ('1331A', 'Electronică Aplicată', 3, 2),
    ('1331B', 'Electronică Aplicată', 3, 2),
    ('1341A', 'Electronică Aplicată', 4, 2),

    -- Rețele și Software de Telecomunicații (RST)
    ('1411A', 'Rețele și Software de Telecomunicații', 1, 2),
    ('1411B', 'Rețele și Software de Telecomunicații', 1, 2),
    ('1421A', 'Rețele și Software de Telecomunicații', 2, 2),
    ('1421B', 'Rețele și Software de Telecomunicații', 2, 2),
    ('1431A', 'Rețele și Software de Telecomunicații', 3, 2),
    ('1431B', 'Rețele și Software de Telecomunicații', 3, 2),
    ('1441A', 'Rețele și Software de Telecomunicații', 4, 2),
    ('1441B', 'Rețele și Software de Telecomunicații', 4, 2),

    -- Inginerie Electrică și Calculatoare (IEC)
    ('1511A', 'Inginerie Electrică și Calculatoare', 1, 2),
    ('1511B', 'Inginerie Electrică și Calculatoare', 1, 2),
    ('1521A', 'Inginerie Electrică și Calculatoare', 2, 2),
    ('1521B', 'Inginerie Electrică și Calculatoare', 2, 2),
    ('1521C', 'Inginerie Electrică și Calculatoare', 2, 2),
    ('1531A', 'Inginerie Electrică și Calculatoare', 3, 2),
    ('1531B', 'Inginerie Electrică și Calculatoare', 3, 2),
    ('1541A', 'Inginerie Electrică și Calculatoare', 4, 2),
    ('1541B', 'Inginerie Electrică și Calculatoare', 4, 2),

    -- Tehnologia Informației (TI)
    ('1611A', 'Tehnologia Informației', 1, 2),
    ('1611B', 'Tehnologia Informației', 1, 2),
    ('1621A', 'Tehnologia Informației', 2, 2),
    ('1621B', 'Tehnologia Informației', 2, 2),
    ('1631A', 'Tehnologia Informației', 3, 2),
    ('1631B', 'Tehnologia Informației', 3, 2),
    ('1641', 'Tehnologia Informației', 4, 2),

    -- Calculatoare (C)
    ('1711A', 'Calculatoare', 1, 2),
    ('1711B', 'Calculatoare', 1, 2),
    ('1711C', 'Calculatoare', 1, 2),
    ('1721A', 'Calculatoare', 2, 2),
    ('1721B', 'Calculatoare', 2, 2),
    ('1722A', 'Calculatoare', 2, 2),
    ('1722B', 'Calculatoare', 2, 2),
    ('1731A', 'Calculatoare', 3, 2),
    ('1731B', 'Calculatoare', 3, 2),
    ('1732A', 'Calculatoare', 3, 2),
    ('1732B', 'Calculatoare', 3, 2),
    ('1741A', 'Calculatoare', 4, 2),
    ('1741B', 'Calculatoare', 4, 2),
    ('1742A', 'Calculatoare', 4, 2),
    ('1742B', 'Calculatoare', 4, 2),

    -- Electromecanică (EM)
    ('1811A', 'Electromecanică', 1, 2),
    ('1811B', 'Electromecanică', 1, 2),
    ('1821A', 'Electromecanică', 2, 2),
    ('1821B', 'Electromecanică', 2, 2),
    ('1831', 'Electromecanică', 3, 2),
    ('1841', 'Electromecanică', 4, 2),

    -- Electromecanică - Beiuș (EMB)
    ('1921', 'Electromecanică - Beiuș', 2, 2),
    ('1931', 'Electromecanică - Beiuș', 3, 2),

    -- Inginerie Economică în Domeniul Electric, Electronic și Energetic (IEDE)
    ('IEDE-I-A', 'Inginerie Economică în Domeniul Electric, Electronic și Energetic', 1, 2),
    ('IEDE-I-B', 'Inginerie Economică în Domeniul Electric, Electronic și Energetic', 1, 2),
    ('IEDE-II', 'Inginerie Economică în Domeniul Electric, Electronic și Energetic', 2, 2),
    ('IEDE-III', 'Inginerie Economică în Domeniul Electric, Electronic și Energetic', 3, 2),
    ('IEDE-IV', 'Inginerie Economică în Domeniul Electric, Electronic și Energetic', 4, 2);

-- =============================================
-- Rooms
-- =============================================
INSERT INTO rooms (name, capacity, type, location) VALUES
    -- Building A
    ('A003', 30, 'Seminar', 'Cladirea A, Sala A003'),
    ('A007', 30, 'Seminar', 'Cladirea A, Sala A007'),
    ('A009', 30, 'Seminar', 'Cladirea A, Sala A009'),
    ('A103', 30, 'Seminar', 'Cladirea A, Sala A103'),
    ('A201', 60, 'Amfiteatru', 'Cladirea A, Sala A201'),
    ('A202', 60, 'Amfiteatru', 'Cladirea A, Sala A202'),
    ('A207', 30, 'Seminar', 'Cladirea A, Sala A207'),
    ('A301', 100, 'Amfiteatru', 'Cladirea A, Sala A301'),

    -- Building B
    ('B01', 30, 'Laborator', 'Cladirea B, Sala B01'),
    ('B02', 30, 'Laborator', 'Cladirea B, Sala B02'),
    ('B03', 30, 'Laborator', 'Cladirea B, Sala B03'),
    ('B05', 30, 'Laborator', 'Cladirea B, Sala B05'),
    ('B06', 30, 'Laborator', 'Cladirea B, Sala B06'),
    ('B07', 30, 'Laborator', 'Cladirea B, Sala B07'),
    ('B08', 30, 'Laborator', 'Cladirea B, Sala B08'),
    ('B112', 30, 'Laborator', 'Cladirea B, Sala B112'),
    ('B212', 30, 'Laborator', 'Cladirea B, Sala B212'),
    ('B215', 30, 'Laborator', 'Cladirea B, Sala B215'),
    ('B223', 30, 'Laborator', 'Cladirea B, Sala B223'),

    -- Building C
    ('C108', 30, 'Laborator', 'Cladirea C, Sala C108'),
    ('C109', 30, 'Laborator', 'Cladirea C, Sala C109'),
    ('C122', 30, 'Laborator', 'Cladirea C, Sala C122'),

    -- Building E
    ('E104', 30, 'Laborator', 'Cladirea E, Sala E104'),
    ('E106', 60, 'Amfiteatru', 'Cladirea E, Sala E106'),
    ('E110', 30, 'Laborator', 'Cladirea E, Sala E110'),
    ('E111', 30, 'Laborator', 'Cladirea E, Sala E111'),
    ('E112', 30, 'Laborator', 'Cladirea E, Sala E112'),
    ('E113', 30, 'Laborator', 'Cladirea E, Sala E113'),

    -- Building L
    ('L205', 30, 'Laborator', 'Cladirea L, Sala L205'),

    -- Building T
    ('T012', 30, 'Laborator', 'Cladirea T, Sala T012'),
    ('T101', 30, 'Laborator', 'Cladirea T, Sala T101'),
    ('T204', 30, 'Laborator', 'Cladirea T, Sala T204'),
    ('T205', 30, 'Laborator', 'Cladirea T, Sala T205'),
    ('T206', 30, 'Laborator', 'Cladirea T, Sala T206'),
    ('T208B', 25, 'Laborator', 'Cladirea T, Sala T208B'),
    ('T208C', 25, 'Laborator', 'Cladirea T, Sala T208C'),
    ('T208D', 25, 'Laborator', 'Cladirea T, Sala T208D'),

    -- Building V
    ('V202', 100, 'Amfiteatru', 'Cladirea V, Sala V202'),
    ('V203', 60, 'Amfiteatru', 'Cladirea V, Sala V203'),
    ('V204', 30, 'Laborator', 'Cladirea V, Sala V204'),
    ('V208', 30, 'Laborator', 'Cladirea V, Sala V208'),
    ('V209', 30, 'Laborator', 'Cladirea V, Sala V209'),
    ('V210', 30, 'Laborator', 'Cladirea V, Sala V210'),
    ('V211', 30, 'Laborator', 'Cladirea V, Sala V211'),
    ('V213B', 25, 'Laborator', 'Cladirea V, Sala V213B'),
    ('V213C', 25, 'Laborator', 'Cladirea V, Sala V213C'),
    ('V214B', 25, 'Laborator', 'Cladirea V, Sala V214B'),
    ('V214C', 25, 'Laborator', 'Cladirea V, Sala V214C');

-- =============================================
-- Subjects (each activity type is a separate entry)
-- =============================================
INSERT INTO subjects (name, activity_type) VALUES
    -- ===== Calculatoare =====
    ('Programare orientată pe obiecte', 'Curs'),
    ('Programare orientată pe obiecte', 'Laborator'),
    ('Elemente de Grafică pe Calculator', 'Curs'),
    ('Elemente de Grafică pe Calculator', 'Laborator'),
    ('Etică și integritate academică', 'Curs'),
    ('Baze de date', 'Curs'),
    ('Baze de date', 'Laborator'),
    ('Structura și Organizarea Calculatoarelor', 'Curs'),
    ('Structura și Organizarea Calculatoarelor', 'Laborator'),
    ('Electronică Digitală II', 'Curs'),
    ('Electronică Digitală II', 'Proiect'),
    ('Electronică Digitală II', 'Laborator'),
    ('Teoria Sistemelor', 'Curs'),
    ('Teoria Sistemelor', 'Laborator'),
    ('Didactica specialității', 'Curs'),
    ('Didactica specialității', 'Seminar'),
    ('Limbă străină IV', 'Seminar'),
    ('Electrotehnică', 'Curs'),
    ('Electrotehnică', 'Laborator'),
    ('Dispozitive electronice și electronică analogică', 'Curs'),
    ('Dispozitive electronice și electronică analogică', 'Laborator'),
    ('Programarea Calculatoarelor și Limbaje de Programare II', 'Curs'),
    ('Programarea Calculatoarelor și Limbaje de Programare II', 'Laborator'),
    ('Proiectare Logică II', 'Curs'),
    ('Proiectare Logică II', 'Laborator'),
    ('Limbă Străină II', 'Seminar'),
    ('Economie Generală', 'Curs'),
    ('Informatică Aplicată II', 'Curs'),
    ('Informatică Aplicată II', 'Laborator'),
    ('Cloud computing', 'Curs'),
    ('Cloud computing', 'Laborator'),
    ('Inginerie Software I', 'Curs'),
    ('Modelare și simulare', 'Curs'),
    ('Modelare și simulare', 'Laborator'),
    ('Prelucrarea Imaginilor', 'Curs'),
    ('Prelucrarea Imaginilor', 'Laborator'),
    ('Prelucrarea Imaginilor', 'Proiect'),
    ('Sisteme Distribuite', 'Curs'),
    ('Sisteme Distribuite', 'Laborator'),
    ('Sisteme Expert', 'Laborator'),
    ('Sisteme de Intrare-Ieșire și Echipamente Periferice', 'Curs'),
    ('Sisteme de Intrare-Ieșire și Echipamente Periferice', 'Proiect'),
    ('Sisteme de Operare Avansate', 'Laborator'),
    ('Sisteme de Operare Avansate', 'Proiect'),
    ('Proiectarea Rețelelor de Calculatoare', 'Curs'),
    ('Proiectarea Rețelelor de Calculatoare', 'Laborator'),
    ('Proiectarea Rețelelor de Calculatoare', 'Proiect'),
    ('Proiectarea cu microprocesoare', 'Curs'),
    ('Proiectarea aplicațiilor pentru dispozitive mobile și web', 'Laborator'),
    ('Integrarea Sistemelor Informatice', 'Curs'),
    ('Integrarea Sistemelor Informatice', 'Laborator'),
    ('Comunicare Multimedia', 'Curs'),
    ('Comunicare Multimedia', 'Seminar'),
    ('Fiabilitate software', 'Curs'),
    ('Fiabilitate software', 'Laborator'),
    ('Achiziția și Prelucrarea Datelor', 'Curs'),
    ('Achiziția și Prelucrarea Datelor', 'Laborator'),
    ('Tehnologii multimedia', 'Curs'),
    ('Tehnologii multimedia', 'Laborator'),
    ('Interfețe și Periferice ale Calculatoarelor', 'Curs'),
    ('Interfețe și Periferice ale Calculatoarelor', 'Laborator'),
    ('Interfețe și Periferice ale Calculatoarelor', 'Proiect'),
    ('Integrarea Dispozitivelor Inteligente în Creșterea Sustenabilității Sistemelor', 'Curs'),
    ('Integrarea Dispozitivelor Inteligente în Creșterea Sustenabilității Sistemelor', 'Laborator'),
    ('Tehnici de comunicare în IT', 'Curs'),
    ('Tehnici de comunicare în IT', 'Seminar'),

    -- ===== Tehnologia Informației =====
    ('Teoria Probabilităților și Statistică Matematică', 'Curs'),
    ('Teoria Probabilităților și Statistică Matematică', 'Laborator'),
    ('Circuite integrate digitale II', 'Curs'),
    ('Circuite integrate digitale II', 'Laborator'),

    -- ===== Pedagogie (shared across specializations) =====
    ('Pedagogie I: Fundamentele pedagogiei; Teoria și metodologia curriculumului', 'Curs'),
    ('Pedagogie I: Fundamentele pedagogiei; Teoria și metodologia curriculumului', 'Seminar'),
    ('Managementul clasei de elevi', 'Curs'),
    ('Managementul clasei de elevi', 'Seminar'),

    -- ===== Automatică și Informatică Aplicată =====
    ('Teoria Sistemelor II', 'Curs'),
    ('Teoria Sistemelor II', 'Laborator'),
    ('Teoria Sistemelor II', 'Seminar'),
    ('Automate și Microprogramare', 'Curs'),
    ('Automate și Microprogramare', 'Laborator'),
    ('Automate și Microprogramare', 'Proiect'),
    ('Informatica Sistemelor de Conducere', 'Curs'),
    ('Informatica Sistemelor de Conducere', 'Laborator'),
    ('Informatica Sistemelor de Conducere', 'Proiect'),
    ('Ingineria Reglării Automate', 'Curs'),
    ('Ingineria Reglării Automate', 'Laborator'),
    ('Ingineria Sistemelor Industriale', 'Curs'),
    ('Ingineria Sistemelor Industriale', 'Laborator'),
    ('Ingineria Sistemelor Industriale', 'Proiect'),
    ('Sisteme cu Microprocesoare', 'Curs'),
    ('Sisteme cu Microprocesoare', 'Laborator'),
    ('Sisteme cu Microprocesoare II', 'Curs'),
    ('Sisteme cu Microprocesoare II', 'Laborator'),
    ('Sisteme de Reglare Avansate', 'Curs'),
    ('Sisteme de Reglare Avansate', 'Laborator'),
    ('Sisteme Dinamice cu Evenimente Discrete', 'Curs'),
    ('Sisteme Dinamice cu Evenimente Discrete', 'Laborator'),
    ('Sisteme Fuzzy și Rețele Neuronale', 'Curs'),
    ('Sisteme Fuzzy și Rețele Neuronale', 'Laborator'),
    ('Sisteme Informatice Industriale', 'Curs'),
    ('Sisteme Informatice Industriale', 'Laborator'),
    ('Conducerea Roboților Industriali', 'Curs'),
    ('Conducerea Roboților Industriali', 'Laborator'),
    ('Conducerea Roboților Industriali', 'Proiect'),
    ('Robotică', 'Curs'),
    ('Robotică', 'Laborator'),
    ('Modelare, Simulare și Identificare II', 'Curs'),
    ('Modelare, Simulare și Identificare II', 'Laborator'),
    ('Proiectarea Asistată în Automatizări', 'Curs'),
    ('Proiectarea Asistată în Automatizări', 'Laborator'),
    ('Proiectarea Asistată în Automatizări', 'Proiect'),
    ('Sisteme de Operare în Automatizări', 'Curs'),
    ('Sisteme de Operare în Automatizări', 'Laborator'),
    ('Programare în Java', 'Curs'),
    ('Programare în Java', 'Laborator'),
    ('Medii de Calcul Ingineresc', 'Curs'),
    ('Medii de Calcul Ingineresc', 'Laborator'),

    -- ===== Sisteme Electrice =====
    ('Teoria Câmpului Electromagnetic', 'Curs'),
    ('Teoria Câmpului Electromagnetic', 'Laborator'),
    ('Teoria Câmpului Electromagnetic', 'Seminar'),
    ('Materiale Electrotehnice', 'Curs'),
    ('Materiale Electrotehnice', 'Laborator'),
    ('Matematici Speciale', 'Curs'),
    ('Matematici Speciale', 'Seminar'),
    ('Mașini Electrice I', 'Curs'),
    ('Mașini Electrice I', 'Laborator'),
    ('Mașini Electrice și Acționări II', 'Curs'),
    ('Mașini Electrice și Acționări II', 'Laborator'),
    ('Mașini Electrice și Acționări II', 'Proiect'),
    ('Teoria Circuitelor Electrice II', 'Curs'),
    ('Teoria Circuitelor Electrice II', 'Laborator'),
    ('Teoria Circuitelor Electrice II', 'Seminar'),
    ('Instalații Electrice', 'Curs'),
    ('Instalații Electrice', 'Laborator'),
    ('Instalații Electrice', 'Proiect'),
    ('Acționări Electrice I', 'Curs'),
    ('Acționări Electrice I', 'Laborator'),
    ('Acționări Electrice I', 'Proiect'),
    ('Utilizarea Energiei Electrice', 'Curs'),
    ('Utilizarea Energiei Electrice', 'Laborator'),
    ('Utilizarea Energiei Electrice', 'Proiect'),
    ('Calitatea Energiei Electrice', 'Curs'),
    ('Calitatea Energiei Electrice', 'Proiect'),
    ('Surse de Energie', 'Curs'),
    ('Surse de Energie', 'Laborator'),
    ('Surse Regenerabile', 'Curs'),
    ('Surse Regenerabile', 'Laborator'),
    ('Sisteme Moderne de Tracțiune Electrică', 'Curs'),
    ('Sisteme Moderne de Tracțiune Electrică', 'Laborator'),
    ('Tracțiune Electrică', 'Curs'),
    ('Tracțiune Electrică', 'Laborator'),
    ('Aparate de Comutație', 'Curs'),
    ('Aparate de Comutație', 'Laborator'),
    ('Monitorizarea și Diagnoza Echipamentelor Electrotehnice', 'Curs'),
    ('Monitorizarea și Diagnoza Echipamentelor Electrotehnice', 'Laborator'),
    ('Asigurarea Calității în Sistemele Electrice', 'Curs'),
    ('Asigurarea Calității în Sistemele Electrice', 'Laborator'),
    ('CAD pentru Echipamente Electrice', 'Curs'),
    ('CAD pentru Echipamente Electrice', 'Laborator'),
    ('Proiectarea Sistemelor Electrice Industriale', 'Curs'),
    ('Proiectarea Sistemelor Electrice Industriale', 'Proiect'),
    ('Tehnica Iluminatului', 'Curs'),
    ('Tehnica Iluminatului', 'Laborator'),

    -- ===== Electronică Aplicată =====
    ('Materiale pentru Electronică', 'Curs'),
    ('Materiale pentru Electronică', 'Laborator'),
    ('Dispozitive Electronice', 'Curs'),
    ('Dispozitive Electronice', 'Laborator'),
    ('Circuite Electronice Liniare', 'Curs'),
    ('Circuite Electronice Liniare', 'Laborator'),
    ('Electronică de Putere', 'Curs'),
    ('Electronică de Putere', 'Laborator'),
    ('Electronică Analogică și Digitală II', 'Curs'),
    ('Electronică Analogică și Digitală II', 'Laborator'),
    ('Electrotehnica Industrială', 'Curs'),
    ('Electrotehnica Industrială', 'Laborator'),
    ('Televiziune', 'Curs'),
    ('Televiziune', 'Laborator'),
    ('Modele SPICE', 'Curs'),
    ('Modele SPICE', 'Laborator'),
    ('Modele SPICE', 'Proiect'),
    ('Aplicații ale Ultrasunetelor', 'Curs'),
    ('Aplicații ale Ultrasunetelor', 'Laborator'),
    ('Instrumentație Electronică de Măsură', 'Curs'),
    ('Instrumentație Electronică de Măsură', 'Laborator'),
    ('Nano și Microtehnologii pentru Electronică', 'Proiect'),
    ('Tehnologie Electronică', 'Curs'),
    ('Tehnologie Electronică', 'Laborator'),
    ('Simularea Circuitelor Electrice', 'Curs'),
    ('Simularea Circuitelor Electrice', 'Laborator'),
    ('Simularea Circuitelor Electrice', 'Proiect'),
    ('Proiectarea Sistemelor Numerice', 'Curs'),
    ('Proiectarea Sistemelor Numerice', 'Laborator'),
    ('Măsurări Electrice și Electronice II', 'Curs'),
    ('Măsurări Electrice și Electronice II', 'Laborator'),

    -- ===== Rețele și Software de Telecomunicații =====
    ('Bazele Electrotehnicii', 'Curs'),
    ('Bazele Electrotehnicii', 'Laborator'),
    ('Bazele Electrotehnicii', 'Seminar'),
    ('Bazele Electrotehnicii I', 'Curs'),
    ('Bazele Electrotehnicii I', 'Seminar'),
    ('Microunde', 'Curs'),
    ('Microunde', 'Laborator'),
    ('Microunde', 'Seminar'),
    ('Tehnologii cu Microunde', 'Curs'),
    ('Tehnologii cu Microunde', 'Laborator'),
    ('Tehnologii cu Microunde', 'Proiect'),
    ('Rețele de Calculatoare', 'Curs'),
    ('Rețele de Calculatoare', 'Laborator'),
    ('Rețele de Comunicații Mobile', 'Curs'),
    ('Rețele de Comunicații Mobile', 'Laborator'),
    ('Arhitecturi de Rețea și Internet', 'Curs'),
    ('Arhitecturi de Rețea și Internet', 'Laborator'),
    ('Sisteme de Comunicații', 'Curs'),
    ('Sisteme de Comunicații', 'Laborator'),
    ('Sisteme de Comunicații', 'Proiect'),
    ('Compresia și Codarea Informației', 'Curs'),
    ('Compresia și Codarea Informației', 'Laborator'),
    ('Compresia și Codarea Informației', 'Proiect'),
    ('Algoritmi de Criptare în Rețele de Telecomunicații', 'Curs'),
    ('Algoritmi de Criptare în Rețele de Telecomunicații', 'Laborator'),
    ('Testarea Echipamentelor de Telecomunicații', 'Curs'),
    ('Testarea Echipamentelor de Telecomunicații', 'Laborator'),
    ('Comunicații Optice', 'Curs'),
    ('Comunicații Optice', 'Laborator'),
    ('Tehnici Moderne de Comutație', 'Curs'),
    ('Tehnici Moderne de Comutație', 'Laborator'),
    ('Teoria Transmisiunii Informației', 'Curs'),
    ('Teoria Transmisiunii Informației', 'Laborator'),
    ('Prelucrarea Semnalelor', 'Curs'),
    ('Prelucrarea Semnalelor', 'Laborator'),
    ('Prelucrarea Numerică a Semnalelor', 'Curs'),
    ('Prelucrarea Numerică a Semnalelor', 'Laborator'),
    ('Semnale și Sisteme', 'Curs'),
    ('Semnale și Sisteme', 'Seminar'),
    ('Prelucrarea și Analiza Imaginilor', 'Curs'),
    ('Prelucrarea și Analiza Imaginilor', 'Proiect'),
    ('Rețele Neurale', 'Curs'),
    ('Rețele Neurale', 'Laborator'),
    ('Rețele Neurale și Sisteme Fuzzy', 'Curs'),
    ('Rețele Neurale și Sisteme Fuzzy', 'Laborator'),
    ('Recunoașterea Formelor', 'Laborator'),
    ('Tehnologii de Programare în Internet', 'Curs'),
    ('Tehnologii de Programare în Internet', 'Laborator'),
    ('Tehnici de Programare', 'Curs'),
    ('Tehnici de Programare', 'Laborator'),

    -- ===== Inginerie Electrică și Calculatoare =====
    ('Metode Numerice', 'Curs'),
    ('Metode Numerice', 'Laborator'),
    ('Metode Numerice', 'Seminar'),
    ('Metode Numerice II', 'Curs'),
    ('Metode Numerice II', 'Laborator'),
    ('Arhitectura Calculatoarelor', 'Curs'),
    ('Arhitectura Calculatoarelor', 'Laborator'),
    ('Convertoare Electronice de Putere', 'Curs'),
    ('Convertoare Electronice de Putere', 'Laborator'),
    ('Convertoare Statice de Putere', 'Curs'),
    ('Convertoare Statice de Putere', 'Laborator'),
    ('Grafică Asistată de Calculator', 'Curs'),
    ('Grafică Asistată de Calculator', 'Laborator'),
    ('Grafică Asistată de Calculator II', 'Curs'),
    ('Grafică Asistată de Calculator II', 'Laborator'),
    ('Grafuri de Legătură în Electrotehnică', 'Curs'),
    ('Grafuri de Legătură în Electrotehnică', 'Laborator'),
    ('Grafuri de Legătură în Electrotehnică I', 'Curs'),
    ('Grafuri de Legătură în Electrotehnică I', 'Laborator'),
    ('Modelarea și Simularea Mașinilor Electrice', 'Curs'),
    ('Modelarea și Simularea Mașinilor Electrice', 'Laborator'),
    ('Sisteme de Operare', 'Laborator'),
    ('Aplicații MATHCAD și MATLAB', 'Curs'),
    ('Aplicații MATHCAD și MATLAB', 'Laborator'),

    -- ===== Electromecanică =====
    ('Rezistența Materialelor și Organe de Mașini', 'Curs'),
    ('Rezistența Materialelor și Organe de Mașini', 'Seminar'),
    ('Sisteme Electro-Hidro-Pneumatice', 'Curs'),
    ('Sisteme Electro-Hidro-Pneumatice', 'Laborator'),
    ('Sisteme Electromecanice II', 'Curs'),
    ('Sisteme Electromecanice II', 'Laborator'),
    ('Sisteme Electronice Industriale', 'Curs'),
    ('Sisteme Electronice Industriale', 'Laborator'),
    ('Utilaje Electromecanice Industriale', 'Curs'),
    ('Utilaje Electromecanice Industriale', 'Laborator'),
    ('Microsisteme Electromecanice', 'Curs'),
    ('Microsisteme Electromecanice', 'Laborator'),
    ('Roboți', 'Curs'),
    ('Roboți', 'Laborator'),
    ('Acționări Electrice', 'Curs'),
    ('Acționări Electrice', 'Laborator'),
    ('Electrotehnologii', 'Curs'),
    ('Electrotehnologii', 'Laborator'),
    ('Electrotehnologii', 'Proiect'),
    ('Tehnologii Electrice', 'Curs'),
    ('Tehnologii Electrice', 'Laborator'),

    -- ===== Electromecanică - Beiuș =====
    ('Limbi Moderne II', 'Seminar'),
    ('Limbi Moderne IV', 'Seminar'),

    -- ===== Inginerie Economică (IEDE) =====
    ('Bazele Economiei', 'Curs'),
    ('Bazele Economiei', 'Seminar'),
    ('Bazele Managementului', 'Curs'),
    ('Bazele Managementului', 'Laborator'),
    ('Programare Obiect-Orientată', 'Curs'),
    ('Programare Obiect-Orientată', 'Laborator'),

    -- ===== Shared / Common =====
    ('Economie Generală', 'Seminar'),
    ('Engleză', 'Seminar');



